README.md
The F.A.Q is not included as the ReadMe.md is becoming to big imho
=> docs: add DAS guide

devnet-2/celestia-node/bootstrap.txt
Add a boostrap.txt file which includes the Digital Ocean region, the IPV4 address, the TCP port, and the PeerID for each of 3 bootstrap nodes.
=> Add boostrap.txt with ip and peer id for 3 bootstrap nodes

README.md, celestia-application.md
fixes links on readme.md and celestia-application.md
=> fixes links on docs

celestia-bridge-node.md
changed the trusted hash part for the bridge node to reflect that its optional
=> Update celestia-bridge-node.md with trusted hash optionality

celestia-light-node.md
Seems like a lot of members using the latest master vs a tagged release.
=> Add tagged release

blockspacerace/gentx/staker-space.json
=> Staker Space

blockspacerace/gentx/galaxydigital.json
=> GalaxyDigital gentx

blockspacerace/gentx/CitadelOne.json
=> Citadel.one blockspacerace gentx

blockspacerace/gentx/figment.json
Adding Figment's gentx for the blockspacerace-0 testnet.
=> adding figment's gentx

blockspacerace/gentx/Alphabet.json
=> add gentx Alphabet

blockspacerace/genesis.json
add genesis.json for blockspacerace
=> chore: add genesis for itn

arabica-8/genesis.json
=> fix: final fixed genesis for arabica-8

arabica-10/peers.txt
Closes https://github.com/celestiaorg/networks/issues/342
I was able to sync a celestia-app node using this persistent peer via [arabica-10.sh](https://gist.github.com/rootulp/515806e8c73867085d065c447e9428b7#file-arabica-10-sh-L30).
=> feat: add arabica-10 peers.txt

README.md
=> Update README.md with version matrix

mocha-4/peers.txt, mocha-4/seeds.txt
=> itrocket mocha-4 peer and seed

.github/workflows/validate-genesis.yml
=> add check for gentx directory exist

.github/workflows/validate.go
=> bug: update constants used in check to be magnitude of utia not tia

.github/workflows/validate-gentx.yml
=> fix: print formatted file correctly

.github/workflows/validate-validator-github.yml
=> add gh user

celestia/StakingCabin.txt, celestia/gentx/StakingCabin.json
=> add StakingCabin gentx and peer

celestia/gentx/figment.json
=> add figment gentx

celestia/gentx/ChainodeTech.json
=> gentx for ChainodeTech

celestia/gentx/w3hitchhiker.json
Because our hardware supplier failed to make our new server available in time, I have to create gentx from our old server. I will submit our real peer info once the new server is ready.
=> Create gentx for W3.Hitchhiker

README.md
Closes https://github.com/celestiaorg/networks/issues/517
=> docs: describe config file location

celestia/seeds.txt
=> feat: add celestia seeds

celestia/seeds.txt
=> fix: bug with seeds.txt on celestia

README.md
=> chore: update readme "Mainnet" -> "Mainnet Beta"

README.md
=> Update README.md with public dashboards

mocha-4/seeds.txt
Updated the seed node for Mocha-4 to be more flexible on migrating.
changed to dns standards
=> Update seeds P-OPS

README.md
=> docs: change grafana link to docs
